# Generated by Django 5.1.5 on 2025-07-03 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=1)),
                ('comm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('from_time', models.CharField(blank=True, max_length=20, null=True)),
                ('to_time', models.CharField(blank=True, max_length=20, null=True)),
                ('from_date', models.CharField(blank=True, max_length=20, null=True)),
                ('to_date', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(default=1)),
                ('comm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
                ('offer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.offers')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('pno', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=50)),
                ('user_code', models.CharField(max_length=50)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('comm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.IntegerField(default=1)),
                ('comm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='api.user')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50)),
                ('is_admin', models.IntegerField(default=0)),
                ('comm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
