# Generated by Django 5.1.5 on 2025-02-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='is_admin',
            field=models.IntegerField(default=0),
        ),
    ]
