# Generated by Django 5.1.5 on 2025-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
