# Generated by Django 5.1.5 on 2025-02-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_join_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.IntegerField(default=1)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='api.user')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='api.user')),
            ],
        ),
    ]
