# Generated by Django 5.1.5 on 2025-02-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='comm_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.community'),
            preserve_default=False,
        ),
    ]
