# Generated by Django 5.1.5 on 2025-02-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_joinrequest_comm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pno',
            field=models.CharField(default='00000 00000', max_length=20),
            preserve_default=False,
        ),
    ]
