# Generated by Django 5.1.5 on 2025-02-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_pno'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='from_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='from_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='to_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='to_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
